services:
  convite-app:
    build: .
    container_name: convite-app
    restart: always
    user: "root"
    ports:
      - "3002:3002"
    env_file:
      - .env.local
    environment:
      - SUPABASE_INTERNAL_URL=http://kong:8000
    networks:
      - convite-supabase
    volumes:
      - ./uploads:/app/public/uploads
      - ./data:/app/.data

networks:
  convite-supabase:
    external: true
    name: convite-supabase_default
